import React from 'react'

import {
  ArrowClockwiseOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  ArrowsExpandOutline,
  ArrowsShrinkOutline,
  CameraOutline,
  CertificateOutline,
  CheckedOutline,
  CircleMoreOutline,
  CircleOutline,
  CirclePlusOutline,
  ClickCopyOutline,
  ComputerOutline,
  CoordOutline,
  CopyOutline,
  CrossCircleOutline,
  CrossOutline,
  DeleatOutline,
  DoubleArrowClockwiseOutline,
  EditOutline,
  ExplainOutline,
  EyeCloseOutline,
  EyeOutline,
  FileOutline,
  FiltrateOutline,
  HomeOutline,
  IdentificationOutline,
  IllustrateOutline,
  InfoCircleOutline,
  LocationOutline,
  MenuOutline,
  MinusOutline,
  MobileScreenOutline,
  MoreOutline,
  OrderDownOutline,
  OrderOutline,
  OrderUpOutline,
  PhotoOutline,
  PlaceOutline,
  PlusOutline,
  QuestionCircleOutline,
  QuestionOutline,
  SOPOutline,
  ScanCodeOutline,
  SearchOutline,
  SettingOutline,
  SuccessCircleOutline,
  SuccessOutline,
  SwapLeftOutline,
  SwapOutline,
  SwapRightOutline,
  SwapVerticalOutline,
  TelephoneOutline,
  ThermometerOutline,
  TimeCircleOutline,
  UploadOutline,
  VerticalAlignTopOutline,
  VolumeOutline,
  WarningCircleOutline,
  WarningOutline,
  WeChatOutline,
} from '@fruits-chain/icons-react-native'

import Code from '../icon/code'

const icons: { name: string; Component: any }[] = [
  { name: 'ArrowClockwiseOutline', Component: ArrowClockwiseOutline },
  { name: 'ArrowDownOutline', Component: ArrowDownOutline },
  { name: 'ArrowLeftOutline', Component: ArrowLeftOutline },
  { name: 'ArrowRightOutline', Component: ArrowRightOutline },
  { name: 'ArrowUpOutline', Component: ArrowUpOutline },
  { name: 'ArrowsExpandOutline', Component: ArrowsExpandOutline },
  { name: 'ArrowsShrinkOutline', Component: ArrowsShrinkOutline },
  { name: 'CameraOutline', Component: CameraOutline },
  { name: 'CertificateOutline', Component: CertificateOutline },
  { name: 'CheckedOutline', Component: CheckedOutline },
  { name: 'CircleMoreOutline', Component: CircleMoreOutline },
  { name: 'CircleOutline', Component: CircleOutline },
  { name: 'CirclePlusOutline', Component: CirclePlusOutline },
  { name: 'ClickCopyOutline', Component: ClickCopyOutline },
  { name: 'ComputerOutline', Component: ComputerOutline },
  { name: 'CoordOutline', Component: CoordOutline },
  { name: 'CopyOutline', Component: CopyOutline },
  { name: 'CrossCircleOutline', Component: CrossCircleOutline },
  { name: 'CrossOutline', Component: CrossOutline },
  { name: 'DeleatOutline', Component: DeleatOutline },
  {
    name: 'DoubleArrowClockwiseOutline',
    Component: DoubleArrowClockwiseOutline,
  },
  { name: 'EditOutline', Component: EditOutline },
  { name: 'ExplainOutline', Component: ExplainOutline },
  { name: 'EyeCloseOutline', Component: EyeCloseOutline },
  { name: 'EyeOutline', Component: EyeOutline },
  { name: 'FileOutline', Component: FileOutline },
  { name: 'FiltrateOutline', Component: FiltrateOutline },
  { name: 'HomeOutline', Component: HomeOutline },
  { name: 'IdentificationOutline', Component: IdentificationOutline },
  { name: 'IllustrateOutline', Component: IllustrateOutline },
  { name: 'InfoCircleOutline', Component: InfoCircleOutline },
  { name: 'LocationOutline', Component: LocationOutline },
  { name: 'MenuOutline', Component: MenuOutline },
  { name: 'MinusOutline', Component: MinusOutline },
  { name: 'MobileScreenOutline', Component: MobileScreenOutline },
  { name: 'MoreOutline', Component: MoreOutline },
  { name: 'OrderDownOutline', Component: OrderDownOutline },
  { name: 'OrderOutline', Component: OrderOutline },
  { name: 'OrderUpOutline', Component: OrderUpOutline },
  { name: 'PhotoOutline', Component: PhotoOutline },
  { name: 'PlaceOutline', Component: PlaceOutline },
  { name: 'PlusOutline', Component: PlusOutline },
  { name: 'QuestionCircleOutline', Component: QuestionCircleOutline },
  { name: 'QuestionOutline', Component: QuestionOutline },
  { name: 'SOPOutline', Component: SOPOutline },
  { name: 'ScanCodeOutline', Component: ScanCodeOutline },
  { name: 'SearchOutline', Component: SearchOutline },
  { name: 'SettingOutline', Component: SettingOutline },
  { name: 'SuccessCircleOutline', Component: SuccessCircleOutline },
  { name: 'SuccessOutline', Component: SuccessOutline },
  { name: 'SwapLeftOutline', Component: SwapLeftOutline },
  { name: 'SwapOutline', Component: SwapOutline },
  { name: 'SwapRightOutline', Component: SwapRightOutline },
  { name: 'SwapVerticalOutline', Component: SwapVerticalOutline },
  { name: 'TelephoneOutline', Component: TelephoneOutline },
  { name: 'ThermometerOutline', Component: ThermometerOutline },
  { name: 'TimeCircleOutline', Component: TimeCircleOutline },
  { name: 'UploadOutline', Component: UploadOutline },
  { name: 'VerticalAlignTopOutline', Component: VerticalAlignTopOutline },
  { name: 'VolumeOutline', Component: VolumeOutline },
  { name: 'WarningCircleOutline', Component: WarningCircleOutline },
  { name: 'WarningOutline', Component: WarningOutline },
  { name: 'WeChatOutline', Component: WeChatOutline },
]

const Outline: React.FC = () => {
  return <Code icons={icons} currentColor={false} />
}

export default Outline
