import React from 'react'

import {
  ArrowClockwiseOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  ArrowsExpandOutline,
  ArrowsShrinkOutline,
  CameraOutline,
  CertificateOutline,
  CircleMoreOutline,
  CircleOutline,
  CirclePlusOutline,
  ClickCopyOutline,
  CommentOutline,
  ComputerOutline,
  CoordOutline,
  CopyOutline,
  CrossCircleOutline,
  CrossOutline,
  DeleteOutline,
  DoubleArrowClockwiseOutline,
  DraftsOutline,
  EditOutline,
  EditPenOutline,
  ExplainOutline,
  ExportOutline,
  EyeCloseOutline,
  EyeOutline,
  FileOutline,
  FiltrateOutline,
  GrassOutline,
  HexagonBarOutline,
  HomeOutline,
  IdentificationOutline,
  IllustrateOutline,
  InfoCircleOutline,
  LikeOutline,
  LocationOutline,
  LockOutline,
  ManOutline,
  MenuOutline,
  MinusOutline,
  MobileScreenOutline,
  MoreOutline,
  MoreRectangleOutline,
  OrderDownOutline,
  OrderOutline,
  OrderUpOutline,
  PhotoOutline,
  PlaceOutline,
  PlusOutline,
  QuestionCircleOutline,
  QuestionOutline,
  RectSuccessOutline,
  SOPOutline,
  ScanCodeOutline,
  SearchOutline,
  SettingOutline,
  StarOutline,
  SuccessCircleOutline,
  SuccessOutline,
  SwapLeftOutline,
  SwapOutline,
  SwapRightOutline,
  SwapVerticalOutline,
  TelephoneOutline,
  ThermometerOutline,
  TimeCircleOutline,
  UploadOutline,
  VerticalAlignTopOutline,
  VolumeOutline,
  WarningCircleOutline,
  WarningOutline,
  WarningTriangleOutline,
  WeChatOutline,
  WomanOutline,
} from '@fruits-chain/icons-react-native'

import Code from '../icon/code'

const icons: { name: string; Component: any }[] = [
  { name: 'ArrowClockwiseOutline', Component: ArrowClockwiseOutline },
  { name: 'ArrowDownOutline', Component: ArrowDownOutline },
  { name: 'ArrowLeftOutline', Component: ArrowLeftOutline },
  { name: 'ArrowRightOutline', Component: ArrowRightOutline },
  { name: 'ArrowUpOutline', Component: ArrowUpOutline },
  { name: 'ArrowsExpandOutline', Component: ArrowsExpandOutline },
  { name: 'ArrowsShrinkOutline', Component: ArrowsShrinkOutline },
  { name: 'CameraOutline', Component: CameraOutline },
  { name: 'CertificateOutline', Component: CertificateOutline },
  { name: 'CircleMoreOutline', Component: CircleMoreOutline },
  { name: 'CircleOutline', Component: CircleOutline },
  { name: 'CirclePlusOutline', Component: CirclePlusOutline },
  { name: 'ClickCopyOutline', Component: ClickCopyOutline },
  { name: 'CommentOutline', Component: CommentOutline },
  { name: 'ComputerOutline', Component: ComputerOutline },
  { name: 'CoordOutline', Component: CoordOutline },
  { name: 'CopyOutline', Component: CopyOutline },
  { name: 'CrossCircleOutline', Component: CrossCircleOutline },
  { name: 'CrossOutline', Component: CrossOutline },
  { name: 'DeleteOutline', Component: DeleteOutline },
  {
    name: 'DoubleArrowClockwiseOutline',
    Component: DoubleArrowClockwiseOutline,
  },
  { name: 'DraftsOutline', Component: DraftsOutline },
  { name: 'EditOutline', Component: EditOutline },
  { name: 'EditPenOutline', Component: EditPenOutline },
  { name: 'ExplainOutline', Component: ExplainOutline },
  { name: 'ExportOutline', Component: ExportOutline },
  { name: 'EyeCloseOutline', Component: EyeCloseOutline },
  { name: 'EyeOutline', Component: EyeOutline },
  { name: 'FileOutline', Component: FileOutline },
  { name: 'FiltrateOutline', Component: FiltrateOutline },
  { name: 'GrassOutline', Component: GrassOutline },
  { name: 'HexagonBarOutline', Component: HexagonBarOutline },
  { name: 'HomeOutline', Component: HomeOutline },
  { name: 'IdentificationOutline', Component: IdentificationOutline },
  { name: 'IllustrateOutline', Component: IllustrateOutline },
  { name: 'InfoCircleOutline', Component: InfoCircleOutline },
  { name: 'LikeOutline', Component: LikeOutline },
  { name: 'LocationOutline', Component: LocationOutline },
  { name: 'LockOutline', Component: LockOutline },
  { name: 'ManOutline', Component: ManOutline },
  { name: 'MenuOutline', Component: MenuOutline },
  { name: 'MinusOutline', Component: MinusOutline },
  { name: 'MobileScreenOutline', Component: MobileScreenOutline },
  { name: 'MoreOutline', Component: MoreOutline },
  { name: 'MoreRectangleOutline', Component: MoreRectangleOutline },
  { name: 'OrderDownOutline', Component: OrderDownOutline },
  { name: 'OrderOutline', Component: OrderOutline },
  { name: 'OrderUpOutline', Component: OrderUpOutline },
  { name: 'PhotoOutline', Component: PhotoOutline },
  { name: 'PlaceOutline', Component: PlaceOutline },
  { name: 'PlusOutline', Component: PlusOutline },
  { name: 'QuestionCircleOutline', Component: QuestionCircleOutline },
  { name: 'QuestionOutline', Component: QuestionOutline },
  { name: 'RectSuccessOutline', Component: RectSuccessOutline },
  { name: 'SOPOutline', Component: SOPOutline },
  { name: 'ScanCodeOutline', Component: ScanCodeOutline },
  { name: 'SearchOutline', Component: SearchOutline },
  { name: 'SettingOutline', Component: SettingOutline },
  { name: 'StarOutline', Component: StarOutline },
  { name: 'SuccessCircleOutline', Component: SuccessCircleOutline },
  { name: 'SuccessOutline', Component: SuccessOutline },
  { name: 'SwapLeftOutline', Component: SwapLeftOutline },
  { name: 'SwapOutline', Component: SwapOutline },
  { name: 'SwapRightOutline', Component: SwapRightOutline },
  { name: 'SwapVerticalOutline', Component: SwapVerticalOutline },
  { name: 'TelephoneOutline', Component: TelephoneOutline },
  { name: 'ThermometerOutline', Component: ThermometerOutline },
  { name: 'TimeCircleOutline', Component: TimeCircleOutline },
  { name: 'UploadOutline', Component: UploadOutline },
  { name: 'VerticalAlignTopOutline', Component: VerticalAlignTopOutline },
  { name: 'VolumeOutline', Component: VolumeOutline },
  { name: 'WarningCircleOutline', Component: WarningCircleOutline },
  { name: 'WarningOutline', Component: WarningOutline },
  { name: 'WarningTriangleOutline', Component: WarningTriangleOutline },
  { name: 'WeChatOutline', Component: WeChatOutline },
  { name: 'WomanOutline', Component: WomanOutline },
]

const Outline: React.FC = () => {
  return <Code icons={icons} currentColor={false} />
}

export default Outline
