import React from 'react'

import {
  ApartmentOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  CircleOutline,
  ClickCopyOutline,
  ContainerExportOutline,
  ContainerImportOutline,
  ContainerOutline,
  ContainerSettingOutline,
  CoordOutline,
  CopyOutline,
  CrossCircleOutline,
  CrossOutline,
  DashboardOutline,
  DataReportOutline,
  DeleatOutline,
  DisplayOutline,
  ExplainOutline,
  EyeCloseOutline,
  EyeOutline,
  FileCarOutline,
  FileChartOutline,
  FileCheckListOutline,
  FileJiuOutline,
  FileRecordOutline,
  FileScreenOutline,
  FileSealOutline,
  FileSearchOutline,
  FileTextOutline,
  FileTransportOutline,
  FileUserOutline,
  FileYuanOutline,
  FiltrateOutline,
  FruitStorageOutline,
  HomeSettingOutline,
  InventoryRecordsOutline,
  MobilePhoneOutline,
  MobileScreenOutline,
  OperatorOutline,
  PlusOutline,
  QuestionCircleOutline,
  QuestionOutline,
  ReceiptOutline,
  SPOOutline,
  SearchOutline,
  SpeedOutline,
  SuccessCircleOutline,
  SuccessOutline,
  SwapLeftOutline,
  SwapOutline,
  SwapRightOutline,
  TargetOutline,
  TaskPanelOutline,
  TeamOutline,
  TelephoneOutline,
  TimeCircleOutline,
  VolumeOutline,
  WarningCircleOutline,
  WeChatOutline,
  YuanCircleOutline,
} from '@fruits-chain/icons-react'

import Code from './code'

const icons = [
  { name: 'ApartmentOutline', Component: ApartmentOutline },
  { name: 'ArrowDownOutline', Component: ArrowDownOutline },
  { name: 'ArrowLeftOutline', Component: ArrowLeftOutline },
  { name: 'ArrowRightOutline', Component: ArrowRightOutline },
  { name: 'ArrowUpOutline', Component: ArrowUpOutline },
  { name: 'CircleOutline', Component: CircleOutline },
  { name: 'ClickCopyOutline', Component: ClickCopyOutline },
  { name: 'ContainerExportOutline', Component: ContainerExportOutline },
  { name: 'ContainerImportOutline', Component: ContainerImportOutline },
  { name: 'ContainerOutline', Component: ContainerOutline },
  { name: 'ContainerSettingOutline', Component: ContainerSettingOutline },
  { name: 'CoordOutline', Component: CoordOutline },
  { name: 'CopyOutline', Component: CopyOutline },
  { name: 'CrossCircleOutline', Component: CrossCircleOutline },
  { name: 'CrossOutline', Component: CrossOutline },
  { name: 'DashboardOutline', Component: DashboardOutline },
  { name: 'DataReportOutline', Component: DataReportOutline },
  { name: 'DeleatOutline', Component: DeleatOutline },
  { name: 'DisplayOutline', Component: DisplayOutline },
  { name: 'ExplainOutline', Component: ExplainOutline },
  { name: 'EyeCloseOutline', Component: EyeCloseOutline },
  { name: 'EyeOutline', Component: EyeOutline },
  { name: 'FileCarOutline', Component: FileCarOutline },
  { name: 'FileChartOutline', Component: FileChartOutline },
  { name: 'FileCheckListOutline', Component: FileCheckListOutline },
  { name: 'FileJiuOutline', Component: FileJiuOutline },
  { name: 'FileRecordOutline', Component: FileRecordOutline },
  { name: 'FileScreenOutline', Component: FileScreenOutline },
  { name: 'FileSealOutline', Component: FileSealOutline },
  { name: 'FileSearchOutline', Component: FileSearchOutline },
  { name: 'FileTextOutline', Component: FileTextOutline },
  { name: 'FileTransportOutline', Component: FileTransportOutline },
  { name: 'FileUserOutline', Component: FileUserOutline },
  { name: 'FileYuanOutline', Component: FileYuanOutline },
  { name: 'FiltrateOutline', Component: FiltrateOutline },
  { name: 'FruitStorageOutline', Component: FruitStorageOutline },
  { name: 'HomeSettingOutline', Component: HomeSettingOutline },
  { name: 'InventoryRecordsOutline', Component: InventoryRecordsOutline },
  { name: 'MobilePhoneOutline', Component: MobilePhoneOutline },
  { name: 'MobileScreenOutline', Component: MobileScreenOutline },
  { name: 'OperatorOutline', Component: OperatorOutline },
  { name: 'PlusOutline', Component: PlusOutline },
  { name: 'QuestionCircleOutline', Component: QuestionCircleOutline },
  { name: 'QuestionOutline', Component: QuestionOutline },
  { name: 'ReceiptOutline', Component: ReceiptOutline },
  { name: 'SPOOutline', Component: SPOOutline },
  { name: 'SearchOutline', Component: SearchOutline },
  { name: 'SpeedOutline', Component: SpeedOutline },
  { name: 'SuccessCircleOutline', Component: SuccessCircleOutline },
  { name: 'SuccessOutline', Component: SuccessOutline },
  { name: 'SwapLeftOutline', Component: SwapLeftOutline },
  { name: 'SwapOutline', Component: SwapOutline },
  { name: 'SwapRightOutline', Component: SwapRightOutline },
  { name: 'TargetOutline', Component: TargetOutline },
  { name: 'TaskPanelOutline', Component: TaskPanelOutline },
  { name: 'TeamOutline', Component: TeamOutline },
  { name: 'TelephoneOutline', Component: TelephoneOutline },
  { name: 'TimeCircleOutline', Component: TimeCircleOutline },
  { name: 'VolumeOutline', Component: VolumeOutline },
  { name: 'WarningCircleOutline', Component: WarningCircleOutline },
  { name: 'WeChatOutline', Component: WeChatOutline },
  { name: 'YuanCircleOutline', Component: YuanCircleOutline },
]

const Outline: React.FC = () => {
  return <Code icons={icons} />
}

export default Outline
